main: ${bukkit.main}
name: ${project.name}
version: ${project.version}
api-version: ${mc-api.version}
description: ${project.description}
author: SmashMc
softdepend: [SmashCore, Multiverse-Core, Profile]