name: Backrooms
main: gg.maga.backrooms.Backrooms
version: '${project.version}'
softdepend: [Multiverse-Core]
api-version: 1.19
author: ReaperMaga & Nyxie
description: Very beautiful backrooms minigame plugin